# Generated by Django 6.0.4 on 2026-04-22 19:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Số điện thoại')),
                ('cccd', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số CCCD/CMND')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Số phòng')),
                ('room_type', models.CharField(choices=[('STANDARD', 'Phòng Thường'), ('DELUXE', 'Phòng Cao cấp'), ('VIP', 'Phòng VIP')], default='STANDARD', max_length=20, verbose_name='Loại phòng')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá 1 đêm (VNĐ)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang trống')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày nhận phòng')),
                ('check_out', models.DateField(verbose_name='Ngày trả phòng')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Trạng thái thanh toán')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.customer', verbose_name='Khách hàng')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Phòng')),
            ],
        ),
    ]
